fix: cicd/ fix vars in pipeline (#68)
* fix vars in pipeline

* test

* second test

* move job files

* test

* go

* test

* test

* true

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -101,8 +101,19 @@ jobs:
 
       - name: Install dependencies
         working-directory: ${{ inputs.working-dir-front }}
-        run: npm ci --prefer-offline
+        run: npm ci
 
       - name: Run lint
         working-directory: ${{ inputs.working-dir-front }}
-        run: npm run lint:ci
+        run:  npm run lint:ci || true
+
+      - name: Check for lint errors
+        working-directory: ${{ inputs.working-dir-front }}
+        run: |
+          ERRORS=$(jq '[.[].errorCount] | add' lint-results.json)
+          if [ "$ERRORS" -gt 0 ]; then
+            echo "❌ $ERRORS lint error(s) found"
+            exit 1
+          else
+            echo "✅ No lint errors found"
+          fi
